# Generated by Django 5.1.4 on 2025-01-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0052_auto_20241030_1757"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="bulk_created",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Annotation was created in bulk mode",
                null=True,
                verbose_name="bulk created",
            ),
        ),
    ]
