# Generated by Django 5.1.9 on 2025-06-02 16:40

import annoying.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0006_alter_organizationmember_deleted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionTimeoutPolicy",
            fields=[
                (
                    "organization",
                    annoying.fields.AutoOneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="session_timeout_policy",
                        serialize=False,
                        to="organizations.organization",
                    ),
                ),
                (
                    "max_session_age",
                    models.IntegerField(
                        default=192,
                        help_text="Number of hours that a session can be active before needing to re-login",
                        verbose_name="Max session age (hours)",
                    ),
                ),
                (
                    "max_time_between_activity",
                    models.IntegerField(
                        default=72,
                        help_text="Number of hours that a session stays active without any activity",
                        verbose_name="Max time (hours) between activity",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
        ),
    ]
