# Generated by Django 5.1.9 on 2025-06-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session_policy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessiontimeoutpolicy",
            name="max_session_age",
            field=models.IntegerField(
                default=11520,
                help_text="Number of minutes that a session can be active before needing to re-login",
                verbose_name="Max session age (minutes)",
            ),
        ),
        migrations.AlterField(
            model_name="sessiontimeoutpolicy",
            name="max_time_between_activity",
            field=models.IntegerField(
                default=4320,
                help_text="Number of minutes that a session stays active without any activity",
                verbose_name="Max time (minutes) between activity",
            ),
        ),
    ]
