# Generated by Django 5.1.9 on 2025-06-05 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session_policy", "0002_alter_sessiontimeoutpolicy_max_session_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessiontimeoutpolicy",
            name="max_session_age",
            field=models.IntegerField(
                default=11520,
                help_text="Number of minutes that a session can be active before needing to re-login",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Max session age (minutes)",
            ),
        ),
        migrations.AlterField(
            model_name="sessiontimeoutpolicy",
            name="max_time_between_activity",
            field=models.IntegerField(
                default=4320,
                help_text="Number of minutes that a session stays active without any activity",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Max time (minutes) between activity",
            ),
        ),
    ]
