# Generated by Django 5.1.10 on 2025-06-24 03:22

import django.db.models.deletion
import django_migration_linter as linter
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_manager", "0012_alter_view_user"),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AddField(
            model_name="filter",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional parent filter to create one-level hierarchy (child filters are AND-merged with parent)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="data_manager.filter",
            ),
        ),
        migrations.AlterField(
            model_name="filter",
            name="index",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Display order among root filters only",
                null=True,
                verbose_name="index",
            ),
        ),
    ]
