# Generated by Django 5.1.10 on 2025-07-01 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_manager", "0013_cleanup_inconsistent_filtergroup_20250624_2119"),
        ("data_manager", "0013_filter_parent_alter_filter_index"),
    ]

    operations = []
