# Generated by Django 5.1.11 on 2025-09-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_manager", "0014_merge_20250701_2259"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="view",
            options={"ordering": ["order", "id"]},
        ),
    ]
