blank_issues_enabled: true
contact_links:
  - name: MLTL Annotate Slack Community
    url: https://slack.labelstud.io/?source=github-1
    about: Ask questions and discuss with other users
  - name: MLTL Annotate Documentation
    url: https://docs.mltl.us/guide/
    about: Check out the official MLTL Annotate documentation
  - name: MLTL Annotate Website
    url: https://labelstud.io/
    about: Visit the MLTL Annotate website for more information
