# Generated by Django 5.1.4 on 2025-01-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_model_providers", "0007_alter_modelproviderconnection_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelproviderconnection",
            name="provider",
            field=models.CharField(
                choices=[
                    ("OpenAI", "OpenAI"),
                    ("AzureOpenAI", "AzureOpenAI"),
                    ("VertexAI", "VertexAI"),
                    ("Gemini", "Gemini"),
                    ("Anthropic", "Anthropic"),
                    ("Custom", "Custom"),
                ],
                default="OpenAI",
                max_length=255,
            ),
        ),
    ]
