# Generated by Django 5.1.10 on 2025-07-16 19:00

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models
from django.db import connection

class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_alter_organizationmember_deleted_at"),
        ("projects", "0028_auto_20241107_1031"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    if connection.vendor == 'postgresql':
        operations = [
            migrations.AddField(
                model_name="project",
                name="search_vector",
                field=models.GeneratedField(
                    db_persist=True,
                    expression=django.db.models.expressions.RawSQL(
                        "setweight(to_tsvector('english', COALESCE(CAST(id AS TEXT), '')), 'A') || setweight(to_tsvector('english', COALESCE(title, '')), 'B') || setweight(to_tsvector('english', COALESCE(SUBSTRING(description, 1, 250000), '')), 'C')",
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                        params=[],
                    ),
                    output_field=django.contrib.postgres.search.SearchVectorField(),
                ),
            )
        ]
    else:
        operations = [
            migrations.AddField(
                model_name='project',
                name='search_vector',
                field=models.TextField(blank=True, null=True),
            ),
        ]