# Generated by Django 5.1.8 on 2025-06-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_userproducttour"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="custom_hotkeys",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom keyboard shortcuts configuration for the user interface",
                null=True,
                verbose_name="custom hotkeys",
            ),
        ),
    ]
