# Generated by Django 5.1.10 on 2025-08-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("io_storages", "0019_azureblobimportstoragelink_row_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="azureblobexportstorage",
            name="status",
            field=models.CharField(
                choices=[
                    ("initialized", "Initialized"),
                    ("queued", "Queued"),
                    ("in_progress", "In progress"),
                    ("failed", "Failed"),
                    ("completed", "Completed"),
                    ("completed_with_errors", "Completed with errors"),
                ],
                default="initialized",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="azureblobimportstorage",
            name="status",
            field=models.CharField(
                choices=[
                    ("initialized", "Initialized"),
                    ("queued", "Queued"),
                    ("in_progress", "In progress"),
                    ("failed", "Failed"),
                    ("completed", "Completed"),
                    ("completed_with_errors", "Completed with errors"),
                ],
                default="initialized",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="gcsexportstorage",
            name="status",
            field=models.CharField(
                choices=[
                    ("initialized", "Initialized"),
                    ("queued", "Queued"),
                    ("in_progress", "In progress"),
                    ("failed", "Failed"),
                    ("completed", "Completed"),
                    ("completed_with_errors", "Completed with errors"),
                ],
                default="initialized",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="gcsimportstorage",
            name="status",
            field=models.CharField(
                choices=[
                    ("initialized", "Initialized"),
                    ("queued", "Queued"),
                    ("in_progress", "In progress"),
                    ("failed", "Failed"),
                    ("completed", "Completed"),
                    ("completed_with_errors", "Completed with errors"),
                ],
                default="initialized",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="localfilesexportstorage",
            name="status",
            field=models.CharField(
                choices=[
                    ("initialized", "Initialized"),
                    ("queued", "Queued"),
                    ("in_progress", "In progress"),
                    ("failed", "Failed"),
                    ("completed", "Completed"),
                    ("completed_with_errors", "Completed with errors"),
                ],
                default="initialized",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="localfilesimportstorage",
            name="status",
            field=models.CharField(
                choices=[
                    ("initialized", "Initialized"),
                    ("queued", "Queued"),
                    ("in_progress", "In progress"),
                    ("failed", "Failed"),
                    ("completed", "Completed"),
                    ("completed_with_errors", "Completed with errors"),
                ],
                default="initialized",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="redisexportstorage",
            name="status",
            field=models.CharField(
                choices=[
                    ("initialized", "Initialized"),
                    ("queued", "Queued"),
                    ("in_progress", "In progress"),
                    ("failed", "Failed"),
                    ("completed", "Completed"),
                    ("completed_with_errors", "Completed with errors"),
                ],
                default="initialized",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="redisimportstorage",
            name="status",
            field=models.CharField(
                choices=[
                    ("initialized", "Initialized"),
                    ("queued", "Queued"),
                    ("in_progress", "In progress"),
                    ("failed", "Failed"),
                    ("completed", "Completed"),
                    ("completed_with_errors", "Completed with errors"),
                ],
                default="initialized",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="s3exportstorage",
            name="status",
            field=models.CharField(
                choices=[
                    ("initialized", "Initialized"),
                    ("queued", "Queued"),
                    ("in_progress", "In progress"),
                    ("failed", "Failed"),
                    ("completed", "Completed"),
                    ("completed_with_errors", "Completed with errors"),
                ],
                default="initialized",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="s3importstorage",
            name="status",
            field=models.CharField(
                choices=[
                    ("initialized", "Initialized"),
                    ("queued", "Queued"),
                    ("in_progress", "In progress"),
                    ("failed", "Failed"),
                    ("completed", "Completed"),
                    ("completed_with_errors", "Completed with errors"),
                ],
                default="initialized",
                max_length=64,
            ),
        ),
    ]
