# Generated by Django 5.1.9 on 2025-09-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("io_storages", "0020_alter_azureblobexportstorage_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="azureblobimportstorage",
            name="recursive_scan",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Perform recursive scan over the container content",
                null=True,
                verbose_name="recursive scan",
            ),
        ),
        migrations.AddField(
            model_name="gcsimportstorage",
            name="recursive_scan",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Perform recursive scan over the bucket content",
                null=True,
                verbose_name="recursive scan",
            ),
        ),
        migrations.AddField(
            model_name="localfilesimportstorage",
            name="recursive_scan",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Perform recursive scan over the directory content",
                null=True,
                verbose_name="recursive scan",
            ),
        ),
    ]
